'''
This is just to simulate getting the response from the API
'''

data = {
    "id": "52289808",
    "dataset_id": "32",
    "characters": "50",
    "power": "8603001",
    "global_rank": "87",
    "warriors": "4",
    "sorcerers": "16",
    "taoists": "12",
    "arbalists": "13",
    "lancers": "5",
    "name": "UNFORGIVEN \u4e61",
    "most_recent": "34",
    "server": {"id": "174", "name": "SA42", "rank": "3"},
    "region": {"id": "5", "name": "SA1", "rank": "9"},
    "roster": {
        "1": {
            "id": "1249545",
            "power": "202876",
            "global_rank": "1836",
            "name": "GuerraNFT",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "1", "name": "Warrior"},
            "region": {"id": "5", "name": "SA1", "rank": "121"},
            "server": {"id": "174", "name": "SA42", "rank": "30"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "1"},
        },
        "2": {
            "id": "1229507",
            "power": "200253",
            "global_rank": "2136",
            "name": "eoDigs",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "154"},
            "server": {"id": "174", "name": "SA42", "rank": "36"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "2"},
        },
        "3": {
            "id": "1249577",
            "power": "196299",
            "global_rank": "2611",
            "name": "Bllue\u30c4",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "190"},
            "server": {"id": "174", "name": "SA42", "rank": "43"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "3"},
        },
        "4": {
            "id": "1249570",
            "power": "195618",
            "global_rank": "2704",
            "name": "Lua Carmesim",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "1", "name": "Warrior"},
            "region": {"id": "5", "name": "SA1", "rank": "198"},
            "server": {"id": "174", "name": "SA42", "rank": "46"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "4"},
        },
        "5": {
            "id": "1249659",
            "power": "189025",
            "global_rank": "3846",
            "name": "Fire Hydrah",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "281"},
            "server": {"id": "174", "name": "SA42", "rank": "65"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "5"},
        },
        "6": {
            "id": "1249603",
            "power": "188485",
            "global_rank": "3947",
            "name": "Top\u4e36\u9b3c\u89c1\u6101\u6101\u6101\u6101\u6101\u6101",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "287"},
            "server": {"id": "174", "name": "SA42", "rank": "67"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "6"},
        },
        "7": {
            "id": "5082135",
            "power": "187002",
            "global_rank": "4255",
            "name": "SD Vit\u00e3o",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "311"},
            "server": {"id": "174", "name": "SA42", "rank": "70"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "7"},
        },
        "8": {
            "id": "1229575",
            "power": "184696",
            "global_rank": "4805",
            "name": "Giilbert",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "356"},
            "server": {"id": "174", "name": "SA42", "rank": "79"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "8"},
        },
        "9": {
            "id": "1249892",
            "power": "184486",
            "global_rank": "4864",
            "name": "abime",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "363"},
            "server": {"id": "174", "name": "SA42", "rank": "80"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "9"},
        },
        "10": {
            "id": "1160120",
            "power": "182882",
            "global_rank": "5339",
            "name": "lishut",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "391"},
            "server": {"id": "174", "name": "SA42", "rank": "86"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "10"},
        },
        "11": {
            "id": "1299676",
            "power": "182534",
            "global_rank": "5454",
            "name": "KS100Choro",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "399"},
            "server": {"id": "174", "name": "SA42", "rank": "87"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "11"},
        },
        "12": {
            "id": "1249949",
            "power": "181903",
            "global_rank": "5671",
            "name": "J\u0472bs",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "415"},
            "server": {"id": "174", "name": "SA42", "rank": "91"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "12"},
        },
        "13": {
            "id": "1209941",
            "power": "181442",
            "global_rank": "5828",
            "name": "Mukuzam",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "428"},
            "server": {"id": "174", "name": "SA42", "rank": "92"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "13"},
        },
        "14": {
            "id": "1831783",
            "power": "181034",
            "global_rank": "5973",
            "name": "Lord Tyra",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "440"},
            "server": {"id": "174", "name": "SA42", "rank": "93"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "14"},
        },
        "15": {
            "id": "1210089",
            "power": "180427",
            "global_rank": "6205",
            "name": "AquariusEras",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "5", "name": "Lancer"},
            "region": {"id": "5", "name": "SA1", "rank": "466"},
            "server": {"id": "174", "name": "SA42", "rank": "96"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "15"},
        },
        "16": {
            "id": "1150133",
            "power": "180345",
            "global_rank": "6236",
            "name": "k i r a e",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "470"},
            "server": {"id": "174", "name": "SA42", "rank": "97"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "16"},
        },
        "17": {
            "id": "1831575",
            "power": "179674",
            "global_rank": "6494",
            "name": "Mazacre",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "491"},
            "server": {"id": "174", "name": "SA42", "rank": "101"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "17"},
        },
        "18": {
            "id": "18155192",
            "power": "178623",
            "global_rank": "6929",
            "name": "japoneixxx",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "535"},
            "server": {"id": "174", "name": "SA42", "rank": "108"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "18"},
        },
        "19": {
            "id": "1150145",
            "power": "177806",
            "global_rank": "7292",
            "name": "Jahblessme",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "562"},
            "server": {"id": "174", "name": "SA42", "rank": "112"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "19"},
        },
        "20": {
            "id": "1210187",
            "power": "175922",
            "global_rank": "8172",
            "name": "LuTaBolusco",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "5", "name": "Lancer"},
            "region": {"id": "5", "name": "SA1", "rank": "617"},
            "server": {"id": "174", "name": "SA42", "rank": "118"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "20"},
        },
        "21": {
            "id": "1210304",
            "power": "175234",
            "global_rank": "8571",
            "name": "LeodaTe",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "646"},
            "server": {"id": "174", "name": "SA42", "rank": "122"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "21"},
        },
        "22": {
            "id": "1210005",
            "power": "175158",
            "global_rank": "8609",
            "name": "Brucex1",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "1", "name": "Warrior"},
            "region": {"id": "5", "name": "SA1", "rank": "650"},
            "server": {"id": "174", "name": "SA42", "rank": "123"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "22"},
        },
        "23": {
            "id": "1210318",
            "power": "174979",
            "global_rank": "8722",
            "name": "\u0416 Raizera",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "657"},
            "server": {"id": "174", "name": "SA42", "rank": "124"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "23"},
        },
        "24": {
            "id": "1210335",
            "power": "173134",
            "global_rank": "9860",
            "name": "DeusAmetista",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "740"},
            "server": {"id": "174", "name": "SA42", "rank": "132"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "24"},
        },
        "25": {
            "id": "1831984",
            "power": "171937",
            "global_rank": "10648",
            "name": "behxi",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "798"},
            "server": {"id": "174", "name": "SA42", "rank": "134"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "25"},
        },
        "26": {
            "id": "1210136",
            "power": "171935",
            "global_rank": "10650",
            "name": "Ghost Oozo",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "5", "name": "Lancer"},
            "region": {"id": "5", "name": "SA1", "rank": "799"},
            "server": {"id": "174", "name": "SA42", "rank": "135"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "26"},
        },
        "27": {
            "id": "1210093",
            "power": "171332",
            "global_rank": "11109",
            "name": "PaidoToledo",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "835"},
            "server": {"id": "174", "name": "SA42", "rank": "138"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "27"},
        },
        "28": {
            "id": "1210096",
            "power": "170534",
            "global_rank": "11730",
            "name": "Kaoz Ph0enix",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "883"},
            "server": {"id": "174", "name": "SA42", "rank": "140"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "28"},
        },
        "29": {
            "id": "1299981",
            "power": "168839",
            "global_rank": "13072",
            "name": "KO0NAN",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "993"},
            "server": {"id": "174", "name": "SA42", "rank": "144"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "29"},
        },
        "30": {
            "id": "1149611",
            "power": "168426",
            "global_rank": "13432",
            "name": "Jotta Angelo",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "1020"},
            "server": {"id": "174", "name": "SA42", "rank": "147"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "30"},
        },
        "31": {
            "id": "1000529",
            "power": "168214",
            "global_rank": "13636",
            "name": "RafaelB",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "1034"},
            "server": {"id": "174", "name": "SA42", "rank": "148"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "31"},
        },
        "32": {
            "id": "1149599",
            "power": "166375",
            "global_rank": "15382",
            "name": "Eijita",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "1189"},
            "server": {"id": "174", "name": "SA42", "rank": "157"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "32"},
        },
        "33": {
            "id": "1210134",
            "power": "166339",
            "global_rank": "15426",
            "name": "LinsCash",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "1193"},
            "server": {"id": "174", "name": "SA42", "rank": "158"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "33"},
        },
        "34": {
            "id": "1210126",
            "power": "165401",
            "global_rank": "16486",
            "name": "Cz Kieds",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "1274"},
            "server": {"id": "174", "name": "SA42", "rank": "162"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "34"},
        },
        "35": {
            "id": "1250437",
            "power": "165227",
            "global_rank": "16722",
            "name": "SaraLapia",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "1296"},
            "server": {"id": "174", "name": "SA42", "rank": "165"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "35"},
        },
        "36": {
            "id": "1210313",
            "power": "165184",
            "global_rank": "16778",
            "name": "Kursliov",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "1303"},
            "server": {"id": "174", "name": "SA42", "rank": "166"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "36"},
        },
        "37": {
            "id": "1280139",
            "power": "164434",
            "global_rank": "17611",
            "name": "Hynde",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "1377"},
            "server": {"id": "174", "name": "SA42", "rank": "172"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "37"},
        },
        "38": {
            "id": "1210338",
            "power": "163977",
            "global_rank": "18192",
            "name": "MontMontana",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "1417"},
            "server": {"id": "174", "name": "SA42", "rank": "175"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "38"},
        },
        "39": {
            "id": "1210419",
            "power": "161730",
            "global_rank": "21078",
            "name": "Garrocha",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "1", "name": "Warrior"},
            "region": {"id": "5", "name": "SA1", "rank": "1660"},
            "server": {"id": "174", "name": "SA42", "rank": "193"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "39"},
        },
        "40": {
            "id": "1130461",
            "power": "161580",
            "global_rank": "21285",
            "name": "MadaraMec",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "1681"},
            "server": {"id": "174", "name": "SA42", "rank": "196"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "40"},
        },
        "41": {
            "id": "1210328",
            "power": "160782",
            "global_rank": "22417",
            "name": "\u00d0emais",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "1764"},
            "server": {"id": "174", "name": "SA42", "rank": "198"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "41"},
        },
        "42": {
            "id": "1210331",
            "power": "159267",
            "global_rank": "24580",
            "name": "Z\u00e9 Lel\u00e9",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "5", "name": "Lancer"},
            "region": {"id": "5", "name": "SA1", "rank": "1928"},
            "server": {"id": "174", "name": "SA42", "rank": "207"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "42"},
        },
        "43": {
            "id": "1300139",
            "power": "159098",
            "global_rank": "24835",
            "name": "aledorf74rp",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "1957"},
            "server": {"id": "174", "name": "SA42", "rank": "210"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "43"},
        },
        "44": {
            "id": "1210383",
            "power": "156673",
            "global_rank": "28665",
            "name": "MissBl4ck",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "2228"},
            "server": {"id": "174", "name": "SA42", "rank": "223"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "44"},
        },
        "45": {
            "id": "1210173",
            "power": "153521",
            "global_rank": "34481",
            "name": "Tessa \u6b7b",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "2599"},
            "server": {"id": "174", "name": "SA42", "rank": "243"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "45"},
        },
        "46": {
            "id": "1210079",
            "power": "151954",
            "global_rank": "37926",
            "name": "ForeseeMe",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "2842"},
            "server": {"id": "174", "name": "SA42", "rank": "256"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "46"},
        },
        "47": {
            "id": "1210460",
            "power": "148828",
            "global_rank": "45617",
            "name": "Waptor",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "2", "name": "Sorcerer"},
            "region": {"id": "5", "name": "SA1", "rank": "3343"},
            "server": {"id": "174", "name": "SA42", "rank": "294"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "47"},
        },
        "48": {
            "id": "1210589",
            "power": "145316",
            "global_rank": "56256",
            "name": "Hellwolf85",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "5", "name": "Lancer"},
            "region": {"id": "5", "name": "SA1", "rank": "4002"},
            "server": {"id": "174", "name": "SA42", "rank": "341"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "48"},
        },
        "49": {
            "id": "1210188",
            "power": "143851",
            "global_rank": "61318",
            "name": "dollskil",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "3", "name": "Taoist"},
            "region": {"id": "5", "name": "SA1", "rank": "4296"},
            "server": {"id": "174", "name": "SA42", "rank": "356"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "49"},
        },
        "50": {
            "id": "1210196",
            "power": "142410",
            "global_rank": "66897",
            "name": "0Rafaelaa0",
            "most_recent": "34",
            "tao_res": None,
            "alliance_id": "0",
            "class": {"id": "4", "name": "Arbalist"},
            "region": {"id": "5", "name": "SA1", "rank": "4636"},
            "server": {"id": "174", "name": "SA42", "rank": "370"},
            "clan": {"id": "52289808", "name": "UNFORGIVEN \u4e61", "rank": "50"},
        },
    },
}